/// <reference types="next" />
/// <reference types="next/image-types/global" />
import "./.next/types/routes.d.ts";
import "./.next/types/root-params.d.ts";

// this file is generated by next.js.
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.
